### ISSUE TITLE
Flutter version 0.7.3 - Engine run configuration was invalid

### ISSUE THREAD

**Issue by Drakirus** [Drakirus/go-flutter-desktop-embedder#2]
```
flutter --version
Flutter 0.7.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3b309bda07 (il y a 12 jours) • 2018-08-28 12:39:24 -0700
Engine • revision af42b6dc95
Tools • Dart 2.1.0-dev.1.0.flutter-ccb16f7282
```

On the `v0.5.1` the embedder is running correctly, but on the latest `0.7.3` it throws 
```
[ERROR:flutter/shell/common/engine.cc(109)] Engine run configuration was invalid.
[ERROR:flutter/shell/platform/embedder/embedder_engine.cc(65)] Could not launch the engine with configuration.
```

**Comment by james-lawrence** [comment]
switching the engine version might resolve the issue. I get the same result in my pr as you have here with the version in the read me.

with same version as you, switching the engine.version to `af42b6dc95bd9f719e43c4e9f29a00640f0f0bba`
```
flutter --version
Flutter 0.7.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3b309bda07 (12 days ago) • 2018-08-28 12:39:24 -0700
Engine • revision af42b6dc95
Tools • Dart 2.1.0-dev.1.0.flutter-ccb16f7282
```

resulted in foundation/platform bitching because it only has 3 defined types.

```dart
/// The platform that user interaction should adapt to target.
///
/// The [defaultTargetPlatform] getter returns the current platform.
enum TargetPlatform {
  /// Android: <https://www.android.com/>
  android,

  /// Fuchsia: <https://fuchsia.googlesource.com/>
  fuchsia,

  /// iOS: <http://www.apple.com/ios/>
  iOS,
}

```
```
flutter: Observatory listening on http://127.0.0.1:42895/
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building StocksApp(dirty, state: StocksAppState#b6ea7):
flutter: Unknown platform.
flutter: linux was not recognized as a target platform. Consider updating the list of TargetPlatforms to
flutter: include this platform.
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      defaultTargetPlatform (package:flutter/src/foundation/platform.dart:67:5)
flutter: #1      new ThemeData (package:flutter/src/material/theme_data.dart:188:18)
flutter: #2      StocksAppState.theme (file:///shared/james-lawrence/development/go-flutter-desktop-embedder/src/github.com/Drakirus/go-flutter-desktop-embedder/example/stocks/flutter_project/stocks/lib/main.dart:72:20)
flutter: #3      StocksAppState.build (file:///shared/james-lawrence/development/go-flutter-desktop-embedder/src/github.com/Drakirus/go-flutter-desktop-embedder/example/stocks/flutter_project/stocks/lib/main.dart:126:14)
flutter: #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3742:27)
flutter: #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3654:15)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
flutter: #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
flutter: #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
flutter: #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
flutter: #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
flutter: #12     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:881:16)
flutter: #13     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:852:5)
flutter: #14     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:798:17)
flutter: #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
flutter: #16     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:797:13)
flutter: #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:689:7)
flutter: #18     runApp (package:flutter/src/widgets/binding.dart:728:7)
flutter: #19     main (file:///shared/james-lawrence/development/go-flutter-desktop-embedder/src/github.com/Drakirus/go-flutter-desktop-embedder/example/stocks/flutter_project/stocks/lib/main.dart:149:3)
flutter: #20     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
flutter: #21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
signal: segmentation fault (core dumped)
```

**Comment by Drakirus** [comment]
`gdb ./go-flutter-desktop-embedder ./core.xxx` says : 
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f187cdfae0c in minikin::WordBreaker::setText(unsigned short const*, unsigned long) ()
   from /tmp/go-flutter-desktop-embedder/flutter/library/linux/libflutter_engine.so
```

**Comment by james-lawrence** [comment]
@Drakirus question I was testing my android app, and it wasn't choking on the font you have in the example app.

mind expanding on what you think the issue is?

**Comment by Drakirus** [comment]
I don't think I can do a better explanation than what is available here [google/flutter-desktop-embedding] (https://github.com/google/flutter-desktop-embedding/blob/master/README.md#fonts)

**Comment by james-lawrence** [comment]
I saw that, but if Roboto is being set by using fontFamily seems like that would resolve the issue.

**Comment by Drakirus** [comment]
loading the correct the ICU data file seems to resolve the issue.

**Comment by james-lawrence** [comment]
where do we get the ICU data file?
